version: '3.8'

services:
  jupyter_notebook:
    image: jupyter/base-notebook:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''
    tty: true
    stdin_open: true
    networks:
      - nvim-jupyter-network

  nvim_setup:
    build:
      context: .
      dockerfile: Dockerfile.nvim
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
    networks:
      - nvim-jupyter-network

networks:
  nvim-jupyter-network:
    driver: bridge
